import { HelpCircle } from 'lucide-react';
import { SEO } from './SEO';

export function FAQPage() {
  const faqs = [
    {
      q: "What is the Brand Kit Generator and how does it help my business?",
      a: "The Brand Kit Generator is an identity helper designed to formulate a cohesive brand personality for your social media channels or business. By selecting a curated vibe preset (such as Minimalist Luxury, Retro, or Earthy) and describing your niche, the tool synthesizes a 5-color palette, Google Font pairings, taglines, clear Instagram bio suggestions under 150 characters, tone adjectives, and social grid layout ideas. This helps you build visual consistency across your profile."
    },
    {
      q: "Can I customize the colors generated by the Brand Kit Generator?",
      a: "Yes, absolutely! The generator is fully interactive. Once your kit is synthesized, you can use the color-picker buttons or type custom hex values in the color editors below the palette. The live visual mockup updates immediately in real-time, allowing you to instantly preview how your custom color choices look together with your primary typography and tagline."
    },
    {
      q: "Is GrowthCaption free to use?",
      a: "Yes! Currently, our core generators for captions, bios, and usernames are completely free to use."
    },
    {
      q: "Do I need to sign up to use the tools?",
      a: "No account is required. You can jump right in and start generating content instantly."
    },
    {
      q: "How does the AI generation work?",
      a: "We use AI models to generate suggestions based on the information and instructions provided."
    },
    {
      q: "Are the generated usernames guaranteed to be unique or available?",
      a: "GrowthCaption generates creative username suggestions, but it cannot guarantee that a username is unique or available. Check the username directly on Instagram before using it."
    },
    {
      q: "Can I use these usernames on Instagram?",
      a: "You can use a generated suggestion if it is available and appropriate for your account. Always check availability directly on Instagram before using it."
    },
    {
      q: "How does the Reels & Video Downloader work?",
      a: "Paste the URL of a supported public Instagram Reel, video, carousel, or photo into the downloader. The tool processes the link and retrieves available media files so you can preview and download them to your device without requiring an account login."
    },
    {
      q: "Can I download media from private Instagram accounts?",
      a: "No. The downloader only supports public posts and accounts that are accessible without requiring a login."
    },
    {
      q: "Can I download Reels in original quality?",
      a: "The available download quality depends on the media provided by the supported public source. GrowthCaption does not guarantee a specific resolution."
    },
    {
      q: "Does the downloader remove watermarks?",
      a: "No. The tool does not claim to remove watermarks. The available media depends on the supported public source."
    },
    {
      q: "Is it legal to download and save reels of other creators?",
      a: "Downloading public Instagram Reels for personal use, offline viewing, research, or inspiration is generally permissible. However, reposting, re-uploading, or using another creator's content for commercial purposes without explicit permission or proper attribution violates copyright laws and platform policies. Always respect creators' intellectual property and credit original owners."
    },
    {
      q: "How does the AI reposition and zoom my photos in the Photo Resizer?",
      a: "Once you upload an image in the Photo Resizer tab, you can click and drag it on desktop or swipe/touch-drag on mobile devices to reposition the photo dynamically. You can also adjust the fine-tuning Zoom scale slider below the canvas to perfectly frame your photo, or click 'Reset Position' to re-center it anytime."
    },
    {
      q: "What is the ALT Text Generator and how does it help?",
      a: "The ALT Text Generator creates descriptive alternative text that can improve accessibility and give users more context about an image."
    },
    {
      q: "How does the Feed Planner store my drafts and layouts?",
      a: "To respect your privacy and eliminate friction, the Feed Planner stores all your drafted captions, publication dates, and visual feed arrangements securely in your browser's local cache. This ensures your aesthetic planning remains saved between visits without requiring any signup or external server connection."
    },
    {
      q: "Can I create profile banners using the Grid Maker?",
      a: "Yes! The Grid Maker splits a single photo into standard grid formats like 3x1, 3x2, or 3x3. You can scale, crop, and reposition your image, then download the resulting high-quality slices sequentially to publish them consecutively on your profile for a seamless, professional giant banner effect."
    },
    {
      q: "Are the generated hashtags tailored to my specific posts?",
      a: "Yes. The Hashtag Generator provides relevant hashtag suggestions based on your post topic, niche, and platform preferences. It organizes suggestions into popular, medium, and niche categories so you can choose a balanced set of tags for your content."
    },
    {
      q: "Does the generator provide live trending hashtags or guarantee reach?",
      a: "No. GrowthCaption generates hashtag suggestions based on your input topics and preferences. It does not provide live Instagram trend or competition data, and hashtag performance will vary depending on your content, audience, and platform behavior."
    },
    {
      q: "How does the Reel Cover Maker work, and what is the 1:1 safe-zone?",
      a: "The Reel Cover Maker allows you to design stunning covers in the 9:16 vertical ratio (1080x1920 pixels). Since Instagram crops covers to a 1:1 square ratio (1080x1080 pixels) on your main profile feed grid, we've integrated a visual 'Grid Safe Zone' overlay. By toggling this guide, you can ensure your main text, titles, and central focus remain completely inside the square area so they never get cut off on your profile feed."
    },
    {
      q: "Does GrowthCaption save my uploaded photos, links, or captions?",
      a: "Never. We enforce rigorous privacy standards. Your uploaded media files and pasted links are processed temporarily in memory to generate your content or fetch public download links, and are never stored, logged, or distributed on any database or persistent storage."
    }
  ];

  return (
    <div className="max-w-4xl mx-auto w-full px-4 py-12 md:py-20">
      <SEO 
        title="Frequently Asked Questions | GrowthCaption"
        description="Find answers to popular questions about AI Instagram caption generators, Reels downloads, hashtag limits, and account safety."
        url="https://growthcaption.com/faq"
        faqs={faqs.map(faq => ({ question: faq.q, answer: faq.a }))}
      />
      <div className="text-center mb-12">
        <h1 className="text-4xl md:text-5xl font-sans font-bold tracking-tight text-stone-900 mb-4">
          FAQ
        </h1>
        <p className="text-stone-500 font-medium text-base md:text-lg flex items-center justify-center gap-2">
          <HelpCircle size={18} className="text-indigo-600" /> Frequently Asked Questions
        </p>
      </div>

      <div className="space-y-6">
        {faqs.map((faq, i) => (
          <div key={i} className="bg-white rounded-3xl p-6 md:p-8 border border-stone-200/80 shadow-[0_8px_30px_rgb(0,0,0,0.02)] hover:-translate-y-[1px] transition-all">
            <h3 className="text-base font-bold text-stone-900 mb-3 uppercase tracking-wider">{faq.q}</h3>
            <p className="text-xs font-medium text-stone-500 leading-relaxed">{faq.a}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
